[package]
name = "geoink"
version = "0.0.2"
edition = "2021"
authors = ["HanSoBored <raihanzxx@gmailcom>"]

[dependencies]
bitflags = "1.3.2"
jni = "0.19.0"
log = "0.4.14"

[lib]
name = "geoink"
crate-type = ["dylib"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"
